# Copy this into a file called `docker-compose.yml`


services:
  cliapp:
    build:
      context: dockerfiles/
      dockerfile: Dockerfile.cliapp

    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
  webapp:
    build: 
      context: dockerfiles/
      dockerfile: Dockerfile.webapp
    ports:
      - 8080:80
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379    
    
  redis:
    image: redis:7-alpine


  